### ISSUE TITLE
defining V(x): defining common function forms and creating ways for the user to describe which function they want to use and define parameter values

### ISSUE THREAD

**Issue by charlotteharrison1** [CharlieRoss2506/actualgroupproject#12]

**Comment by CharlieRoss2506** [comment]
are we still wanting to do this as we have a completely generalised form for user defined potentials

**Comment by charlotteharrison1** [comment]
> are we still wanting to do this as we have a completely generalised form for user defined potentials

I think it's still worth adding the option for some preset potentials, since the user defined potentials now require the user to input using numpy

**Comment by charlotteharrison1** [comment]
> > are we still wanting to do this as we have a completely generalised form for user defined potentials
> 
> I think it's still worth adding the option for some preset potentials, since the user defined potentials now require the user to input using numpy

I edited the part of the code where you input v(x) to allow for a preset option, which I arbitrarily defined x^2 but can be easily amended in future to allow editing of parameters w/in preset form (like selecting order of polynomial, whether or not it is polynomial or trigonometric, etc)


the definition of V is as follows:
```

#defining V
def V():
    
    print('how would you like to input potential?')
    print('---')
    print('1. preset format')
    print('2. custom')
    porc = int(input('enter your preference:'))

    if porc == 1: 
        vdef = x_array**2
        return(vdef)
    
    elif porc == 2:
        String = str(input("Please input potential using Python.numpy formatting."))
        command = """def f(x): 
            return """ + String
        exec(command, globals())
        
        return f(x_array)
        
    
    else:
        print('please enter only either 1 or 2 to indicate your preference')
        #how do i stop the function in this case?
        
```

**Comment by charlotteharrison1** [comment]
> > > are we still wanting to do this as we have a completely generalised form for user defined potentials
> > 
> > 
> > I think it's still worth adding the option for some preset potentials, since the user defined potentials now require the user to input using numpy
> 
> I edited the part of the code where you input v(x) to allow for a preset option, which I arbitrarily defined x^2 but can be easily amended in future to allow editing of parameters w/in preset form (like selecting order of polynomial, whether or not it is polynomial or trigonometric, etc)
> 
> the definition of V is as follows:
> 
> ```
> 
> #defining V
> def V():
>     
>     print('how would you like to input potential?')
>     print('---')
>     print('1. preset format')
>     print('2. custom')
>     porc = int(input('enter your preference:'))
> 
>     if porc == 1: 
>         vdef = x_array**2
>         return(vdef)
>     
>     elif porc == 2:
>         String = str(input("Please input potential using Python.numpy formatting."))
>         command = """def f(x): 
>             return """ + String
>         exec(command, globals())
>         
>         return f(x_array)
>         
>     
>     else:
>         print('please enter only either 1 or 2 to indicate your preference')
>         #how do i stop the function in this case?
>         
> ```

However, there is the issue here of the user inputting an option other than 1 or 2, which just returns a default error. It would be useful to be able to give a customised error with a message like that which I put in the 'else' statement

**Comment by charlotteharrison1** [comment]
> > > > are we still wanting to do this as we have a completely generalised form for user defined potentials
> > > 
> > > 
> > > I think it's still worth adding the option for some preset potentials, since the user defined potentials now require the user to input using numpy
> > 
> > 
> > I edited the part of the code where you input v(x) to allow for a preset option, which I arbitrarily defined x^2 but can be easily amended in future to allow editing of parameters w/in preset form (like selecting order of polynomial, whether or not it is polynomial or trigonometric, etc)
> > the definition of V is as follows:
> > ```
> > 
> > #defining V
> > def V():
> >     
> >     print('how would you like to input potential?')
> >     print('---')
> >     print('1. preset format')
> >     print('2. custom')
> >     porc = int(input('enter your preference:'))
> > 
> >     if porc == 1: 
> >         vdef = x_array**2
> >         return(vdef)
> >     
> >     elif porc == 2:
> >         String = str(input("Please input potential using Python.numpy formatting."))
> >         command = """def f(x): 
> >             return """ + String
> >         exec(command, globals())
> >         
> >         return f(x_array)
> >         
> >     
> >     else:
> >         print('please enter only either 1 or 2 to indicate your preference')
> >         #how do i stop the function in this case?
> >         
> > ```
> 
> However, there is the issue here of the user inputting an option other than 1 or 2, which just returns a default error. It would be useful to be able to give a customised error with a message like that which I put in the 'else' statement

added a default V value which should act as a good enough failsafe
