### ISSUE TITLE
Use of Widgets 

### ISSUE THREAD

**Issue by Zhap053** [CharlieRoss2506/actualgroupproject#13]
![image](https://user-images.githubusercontent.com/65609731/201383960-67af6ad0-cc10-42e6-9433-b5f6243590f1.png)

I've been trying to figure out today how to use widgets for plotting - using ipywidgets. 

I think I can put ...
- sliders into the code for parameters that appear on the graph plot. 
- Multiple check boxes for which function a user wants to use for V(x).
- (and maybe a box that you hit to download the data directly onto the computer?)

These widgets will make it easy for a user to change how they want to solve the TDSE without having to input into the command line.
I think it will help take away the possibility of errors that a user can create (e.g. putting a letter as an input instead of a number). Plus, will help us save time on writing error code. 

I am however having trouble implementing these widgets on an animated plot. I can only seem to do it on still plots for now. 

Do you guys think this could be a good?

**Comment by Zhap053** [comment]
Here is a page of widgets that can be used:

https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html

**Comment by CharlieRoss2506** [comment]
![th](https://user-images.githubusercontent.com/116881114/201388318-3572bcef-106c-4a18-b537-ca0c3f6fdbae.jpg)

**Comment by CharlieRoss2506** [comment]
Luca this is great, we going to try to implement this now,

**Comment by Zhap053** [comment]
Here is some code for a time evolution slider:

**Comment by Zhap053** [comment]
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
plt.rcParams["axes.labelsize"] = 16


# Input parameters
Nx = 500
xmin = -5
xmax = 5

Nt = 250
tmin = 0
tmax = 20
k = 1

# Calculate grid, potential, and initial wave function
x_array = np.linspace(xmin, xmax, Nx)
t_array = np.linspace(tmin, tmax, Nt)
V_x = k*x_array**2
psi = np.exp(-(x_array+2)**2)

# Calculate finite difference elements
dt = t_array[1] - t_array[0]
dx = x_array[1] - x_array[0]

# Put V(x) array values into the diagonal elements of an empty matrix
V_x_matrix = diags(V_x)

# Calculate the Hamiltonian matrix
H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

# Apply boundary conditions to the Hamiltonian
H[0, :] = H[-1, :] = 0
H[0, 0] = H[-1, -1] = 1

# Calculate U
I_plus = eye(Nx) + 1j * dt / 2. * H
I_minus = eye(Nx) - 1j * dt / 2. * H
U = inv(I_minus).dot(I_plus)

# Iterate over each time, appending each calculation of psi to a list
psi_list = []
for t in t_array:
    psi = U.dot(psi)
    psi[0] = psi[-1] = 0
    psi_list.append(np.abs(psi))
print(psi_list[1])

# Define initial parameters for time evolution
initial_Time = 0

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 1)
ax.grid()

# Simultaneous plot with own axis
ax_twin = ax.twinx()
ax_twin.plot(x_array, V_x, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

# adjust the main plot to make room for the sliders
fig.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the time evolution.
axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
time_slider = Slider(
    ax=axTime,
    label='Time',
    valmin=0,
    valmax=249,
    valinit=initial_Time,
)
print(time_slider)

# The function to be called anytime a slider's value changes
def update(val):
    # problem here
    line.set_ydata(psi_list[int(time_slider.val)])
    fig.canvas.draw_idle()

# register the update function with each slider
time_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')

def reset(event):
    time_slider.reset()

button.on_clicked(reset)

plt.show()

**Comment by Zhap053** [comment]
`from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
plt.rcParams["axes.labelsize"] = 16


# Input parameters
Nx = 500
xmin = -5
xmax = 5

Nt = 250
tmin = 0
tmax = 20
k = 1

# Calculate grid, potential, and initial wave function
x_array = np.linspace(xmin, xmax, Nx)
t_array = np.linspace(tmin, tmax, Nt)
V_x = k*x_array**2
psi = np.exp(-(x_array+2)**2)

# Calculate finite difference elements
dt = t_array[1] - t_array[0]
dx = x_array[1] - x_array[0]

# Put V(x) array values into the diagonal elements of an empty matrix
V_x_matrix = diags(V_x)

# Calculate the Hamiltonian matrix
H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

# Apply boundary conditions to the Hamiltonian
H[0, :] = H[-1, :] = 0
H[0, 0] = H[-1, -1] = 1

# Calculate U
I_plus = eye(Nx) + 1j * dt / 2. * H
I_minus = eye(Nx) - 1j * dt / 2. * H
U = inv(I_minus).dot(I_plus)

# Iterate over each time, appending each calculation of psi to a list
psi_list = []
for t in t_array:
    psi = U.dot(psi)
    psi[0] = psi[-1] = 0
    psi_list.append(np.abs(psi))
print(psi_list[1])

# Define initial parameters for time evolution
initial_Time = 0

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 1)
ax.grid()

# Simultaneous plot with own axis
ax_twin = ax.twinx()
ax_twin.plot(x_array, V_x, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

# adjust the main plot to make room for the sliders
fig.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the time evolution.
axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
time_slider = Slider(
    ax=axTime,
    label='Time',
    valmin=0,
    valmax=249,
    valinit=initial_Time,
)
print(time_slider)

# The function to be called anytime a slider's value changes
def update(val):
    # problem here
    line.set_ydata(psi_list[int(time_slider.val)])
    fig.canvas.draw_idle()

# register the update function with each slider
time_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')

def reset(event):
    time_slider.reset()

button.on_clicked(reset)

plt.show()

`

**Comment by Zhap053** [comment]
```
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
plt.rcParams["axes.labelsize"] = 16


# Input parameters
Nx = 500
xmin = -5
xmax = 5

Nt = 250
tmin = 0
tmax = 20
k = 1

# Calculate grid, potential, and initial wave function
x_array = np.linspace(xmin, xmax, Nx)
t_array = np.linspace(tmin, tmax, Nt)
V_x = k*x_array**2
psi = np.exp(-(x_array+2)**2)

# Calculate finite difference elements
dt = t_array[1] - t_array[0]
dx = x_array[1] - x_array[0]

# Put V(x) array values into the diagonal elements of an empty matrix
V_x_matrix = diags(V_x)

# Calculate the Hamiltonian matrix
H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

# Apply boundary conditions to the Hamiltonian
H[0, :] = H[-1, :] = 0
H[0, 0] = H[-1, -1] = 1

# Calculate U
I_plus = eye(Nx) + 1j * dt / 2. * H
I_minus = eye(Nx) - 1j * dt / 2. * H
U = inv(I_minus).dot(I_plus)

# Iterate over each time, appending each calculation of psi to a list
psi_list = []
for t in t_array:
    psi = U.dot(psi)
    psi[0] = psi[-1] = 0
    psi_list.append(np.abs(psi))
print(psi_list[1])

# Define initial parameters for time evolution
initial_Time = 0

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 1)
ax.grid()
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
plt.rcParams["axes.labelsize"] = 16


# Input parameters
Nx = 500
xmin = -5
xmax = 5

Nt = 250
tmin = 0
tmax = 20
k = 1

# Calculate grid, potential, and initial wave function
x_array = np.linspace(xmin, xmax, Nx)
t_array = np.linspace(tmin, tmax, Nt)
V_x = k*x_array**2
psi = np.exp(-(x_array+2)**2)

# Calculate finite difference elements
dt = t_array[1] - t_array[0]
dx = x_array[1] - x_array[0]

# Put V(x) array values into the diagonal elements of an empty matrix
V_x_matrix = diags(V_x)

# Calculate the Hamiltonian matrix
H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

# Apply boundary conditions to the Hamiltonian
H[0, :] = H[-1, :] = 0
H[0, 0] = H[-1, -1] = 1

# Calculate U
I_plus = eye(Nx) + 1j * dt / 2. * H
I_minus = eye(Nx) - 1j * dt / 2. * H
U = inv(I_minus).dot(I_plus)

# Iterate over each time, appending each calculation of psi to a list
psi_list = []
for t in t_array:
    psi = U.dot(psi)
    psi[0] = psi[-1] = 0
    psi_list.append(np.abs(psi))
print(psi_list[1])

# Define initial parameters for time evolution
initial_Time = 0

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 1)
ax.grid()

# Simultaneous plot with own axis
ax_twin = ax.twinx()
ax_twin.plot(x_array, V_x, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

# adjust the main plot to make room for the sliders
fig.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the time evolution.
axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
time_slider = Slider(
    ax=axTime,
    label='Time',
    valmin=0,
    valmax=249,
    valinit=initial_Time,
)
print(time_slider)

# The function to be called anytime a slider's value changes
def update(val):
    # problem here
    line.set_ydata(psi_list[int(time_slider.val)])
    fig.canvas.draw_idle()

# register the update function with each slider
time_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')

def reset(event):
    time_slider.reset()

button.on_clicked(reset)

plt.show()



# Simultaneous plot with own axis
ax_twin = ax.twinx()
ax_twin.plot(x_array, V_x, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

# adjust the main plot to make room for the sliders
fig.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the time evolution.
axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
time_slider = Slider(
    ax=axTime,
    label='Time',
    valmin=0,
    valmax=249,
    valinit=initial_Time,
)
print(time_slider)

# The function to be called anytime a slider's value changes
def update(val):
    # problem here
    line.set_ydata(psi_list[int(time_slider.val)])
    fig.canvas.draw_idle()

# register the update function with each slider
time_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')

def reset(event):
    time_slider.reset()

button.on_clicked(reset)

plt.show()
```

**Comment by Zhap053** [comment]
![image](https://user-images.githubusercontent.com/65609731/201468816-395ea144-48b6-4841-a575-47730dc18d2b.png)

```
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation

plt.rcParams["axes.labelsize"] = 16


def plot_func():
    # Input parameters
    Nx = 500
    xmin = -5
    xmax = 5

    Nt = 250
    tmin = 0
    tmax = 20
    k = 1

    # Calculate grid, potential, and initial wave function
    x_array = np.linspace(xmin, xmax, Nx)
    t_array = np.linspace(tmin, tmax, Nt)
    V_x = k*x_array**2
    psi = np.exp(-(x_array+2)**2)

    # Calculate finite difference elements
    dt = t_array[1] - t_array[0]
    dx = x_array[1] - x_array[0]

    # Put V(x) array values into the diagonal elements of an empty matrix
    V_x_matrix = diags(V_x)

    # Calculate the Hamiltonian matrix
    H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

    # Apply boundary conditions to the Hamiltonian
    H[0, :] = H[-1, :] = 0
    H[0, 0] = H[-1, -1] = 1

    # Calculate U
    I_plus = eye(Nx) + 1j * dt / 2. * H
    I_minus = eye(Nx) - 1j * dt / 2. * H
    U = inv(I_minus).dot(I_plus)

    # Iterate over each time, appending each calculation of psi to a list
    psi_list = []
    for t in t_array:
        psi = U.dot(psi)
        psi[0] = psi[-1] = 0
        psi_list.append(np.abs(psi))
    print(psi_list[1])

    # Define initial parameters for time evolution
    initial_Time = 0

    # Create the figure and the line that we will manipulate
    fig, ax = plt.subplots()
    line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
    ax.set_xlabel("x [arb units]")
    ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
    ax.set_xlim(x_array[0], x_array[-1])
    ax.set_ylim(0, 1)
    ax.grid()

    ax_twin = ax.twinx()
    ax_twin.plot(x_array, V_x, color="C1")
    ax_twin.set_ylabel("V(x) [arb units]", color="C1")


    # adjust the main plot to make room for the sliders
    fig.subplots_adjust(left=0.25, bottom=0.25)

    # Make a horizontal slider to control the Time evolution.
    axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
    time_slider = Slider(
        ax=axTime,
        label='Time',
        valmin=0,
        valmax=249,
        valinit=initial_Time,
    )
    print(time_slider)

    # The function to be called anytime a slider's value changes
    def update(val):
        # problem here
        line.set_ydata(psi_list[int(time_slider.val)])
        fig.canvas.draw_idle()

    # register the update function with each slider
    time_slider.on_changed(update)

    # Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
    resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
    button = Button(resetax, 'Reset', hovercolor='0.975')

    def reset(event):
        time_slider.reset()

    button.on_clicked(reset)

    plt.show()


plot_func()
```

**Comment by Zhap053** [comment]
Also, should the |wf| be squared to get probability?

**Comment by CharlieRoss2506** [comment]
no, should just be the modulus of the wave function

**Comment by CharlieRoss2506** [comment]
this is brilliant though, will now close this issue as its solved
