### ISSUE TITLE
Alternative code idea

### ISSUE THREAD

**Issue by Zhap053** [CharlieRoss2506/actualgroupproject#35]
![image](https://user-images.githubusercontent.com/65609731/202514947-a2d00288-679e-4bd4-ab95-a9c36f7376b3.png)

**Comment by Zhap053** [comment]
`from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
import pandas as pd
plt.rcParams["axes.labelsize"] = 16

def plot_func(Nx=500, xmin=-5, xmax=5, tmin=0, tmax=20, V_x='x**2'):

    """
    This function solves the Schrödinger's Equation in numerically. It allows
    a user to define their own parameters for space and time. It also allows
    a user to input their own potential equation.

    The function also saves the simulated data automatically in a csv file, plots the solution
    with the ability of a user being able to change the time evolution wth a slider,
    and with use of a button a user can create and download a gif file with an animated 
    version of the solution with time evolution (Its slow so please allow some time), and a user can download data
    into a csv file. 



    User input parameters for function...

    Nx: number of spacial points (=Nt also)
    xmin: minimum spacial-value
    xmax: maximum spacial-value
    tmin: minimum time
    tmax: maximum time
    V_x: Potential equation 



    Example of input parameters for the function to solve schrodinger equation...

    plot_func(Nx=500, xmin=-5, xmax=5, Nt=500, tmin=0, tmax=20, V_x='x**2'



    Example of possible potential equations a user can input when asked use...

    V_x = 'x'
    V_x = 'x**2'
    V_x = 'x**3'
    V_x = 'np.sin(x)'
    V_x = 'np.cos(x)'
    V_x = 'np.sqrt(x)'
    V_x = 'np.exp(x)'
    etc...
    As can be seen the user must use x as the independent variable. They must type the equation 
    in the form of a string. Also, numpy package math functions can be used with in 
    the statement too. 



    These are the packages needed for the funcion to work...

    from matplotlib.widgets import Slider, Button
    import numpy as np
    import matplotlib.pyplot as plt
    from findiff import FinDiff
    from scipy.sparse.linalg import inv
    from scipy.sparse import eye, diags
    import matplotlib.animation as animation
    import pandas as pd
    plt.rcParams["axes.labelsize"] = 16 t



    """

    ###Generating data###

    # Calculate grid, and initial wave function
    Nt = Nx
    x_array = np.linspace(xmin, xmax, Nx)
    t_array = np.linspace(tmin, tmax, Nt)
    psi = np.exp(-(x_array+2)**2)
    # Create potential equation with user input
    V_x = V_x.replace('x', 'x_array')
    V_x = eval(V_x)

    # Calculate finite difference elements
    dt = t_array[1] - t_array[0]
    dx = x_array[1] - x_array[0]

    # Put V(x) array values into the diagonal elements of an empty matrix
    V_x_matrix = diags(V_x)

    # Calculate the Hamiltonian matrix
    H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

    # Apply boundary conditions to the Hamiltonian
    H[0, :] = H[-1, :] = 0
    H[0, 0] = H[-1, -1] = 1

    # Calculate U
    I_plus = eye(Nx) + 1j * dt / 2. * H
    I_minus = eye(Nx) - 1j * dt / 2. * H
    U = inv(I_minus).dot(I_plus)

    # Iterate over each time, appending each calculation of psi to a list
    psi_list = []
    for t in t_array:
        psi = U.dot(psi)
        psi[0] = psi[-1] = 0
        psi_list.append(np.abs(psi))

    # Saves key data into a csv file
    df = pd.DataFrame({'x': x_array, 'time': t_array, 'V(x)': V_x, 'psi': psi_list})



    ###Plotting###

    # Define initial parameters for time evolution
    initial_Time = 0

    # Create the figure and the line that we will manipulate
    fig, ax = plt.subplots()
    line, = ax.plot(x_array, psi_list[initial_Time], lw=2)
    ax.set_xlabel("x [arb units]")
    ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
    ax.set_xlim(x_array[0], x_array[-1])
    ax.set_ylim(0, 2)
    ax.grid()

    ax_twin = ax.twinx()
    ax_twin.plot(x_array, V_x, color="C1")
    ax_twin.set_ylabel("V(x) [arb units]", color="C1")


    # adjust the main plot to make room for the sliders
    fig.subplots_adjust(left=0.25, bottom=0.25)



    ###Widgets for plot###


    # Make a horizontal slider to control the time evolution.
    axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
    time_slider = Slider(
        ax=axTime,
        label='Time',
        valmin=0,
        valmax=len(t_array)- 1,
        valinit=initial_Time,)

    # The function to be called anytime a slider's value changes
    def update(val):
        
        line.set_ydata(psi_list[int(time_slider.val)])
        fig.canvas.draw_idle()

    # Register the update function with each slider
    time_slider.on_changed(update)


    # Create a `matplotlib.widgets.Button` to allow user to download data in csv file.
    dataax = fig.add_axes([0.8, 0.025, 0.18, 0.04])
    button1 = Button(dataax, 'Download Data', hovercolor='0.975')

    def download_data(event):
        
        df.to_csv('psi_data.csv')

    button1.on_clicked(download_data)


    # Create a `matplotlib.widgets.Button` to allow user to download an animated gif
    gifax = fig.add_axes([0.1, 0.025, 0.18, 0.04])
    button2 = Button(gifax, 'Gif Download?', hovercolor='0.975')

    def gif(event):

        # Closes plot to avoid programme freezing (still not working though!!!)
        plt.close(fig)

        # Creates a gif of the simulated data and saves it if button is clicked
        def run(psi):
            line.set_data(x_array, np.abs(psi)**2)
            return line,

        ani = animation.FuncAnimation(fig, run, psi_list, interval=10)
        ani.save("particle_in_a_well.gif", fps=120, dpi=300) 

    button2.on_clicked(gif)


    plt.show()


    ### Need to put into code somehow### 

    # Use your implementation to produce a numerical solution to the particle in a well. 
    # Then, by reading in the data it creates, estimate the frequency of the oscillations. 
    # There are several ways you can do this, but you may consider tracking the peak of the probability distribution 
    # as a function of time.


plot_func()`

**Comment by Zhap053** [comment]
Everything works apart for the Gif button ... it just crashes the programe and I can't figure out why.

**Comment by Zhap053** [comment]
If you wait though you do get a saved gif of the plot

**Comment by charlotteharrison1** [comment]
Just tried to have a look at this, but I'm struggling to run it since I don't think I have the formatting done correctly in my version. Looking at it though, the main differences from the original code seem to be that you have a better user interface for the plot/ animation and that you've used eval() instead of global() to get user inputs, is this right?

If this is the case, I think both of these things would be really good to implement into the initial code, so I think it would be a good idea to merge them :)

**Comment by charlotteharrison1** [comment]
> Everything works apart for the Gif button ... it just crashes the programe and I can't figure out why.

if you could upload this as a pull request you should be able to keep all the original formatting allowing the rest of us to run it and possibly have a look as to why this might be happening

**Comment by charlotteharrison1** [comment]
> > Everything works apart for the Gif button ... it just crashes the programe and I can't figure out why.
> 
> if you could upload this as a pull request you should be able to keep all the original formatting allowing the rest of us to run it and possibly have a look as to why this might be happening

or just put it in the branch I made for this

**Comment by Zhap053** [comment]
Thank you. I have committed it in the new branch. The file name is Slider.py

**Comment by Zhap053** [comment]
import pandas as pd
from matplotlib.widgets import Slider, Button


Also, these are two extra packages you need with my code. That maybe why it doesn't work. But maybe not.

**Comment by Zhap053** [comment]
> Just tried to have a look at this, but I'm struggling to run it since I don't think I have the formatting done correctly in my version. Looking at it though, the main differences from the original code seem to be that you have a better user interface for the plot/ animation and that you've used eval() instead of global() to get user inputs, is this right?
> 
> If this is the case, I think both of these things would be really good to implement into the initial code, so I think it would be a good idea to merge them :)

Yes, I think this is correct.

**Comment by Zhap053** [comment]
I've add some more stuff

**Comment by Zhap053** [comment]
![image](https://user-images.githubusercontent.com/65609731/202801632-3183782a-2e4a-4a6f-b299-c7f0d8dc23fe.png)

**Comment by Zhap053** [comment]
`from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
from matplotlib.widgets import TextBox
import pandas as pd
plt.rcParams["axes.labelsize"] = 16




###Generating data###

def my_func(Nx = 500, xmin = -5, xmax = 5, tmin = 0, tmax = 20, V_x='x**2'):


    # Calculate grid, and initial wave function
    Nt = Nx
    x_array = np.linspace(xmin, xmax, Nx)
    t_array = np.linspace(tmin, tmax, Nt)
    psi = np.exp(-(x_array+2)**2)
    # Create potential equation with user input
    V_x = V_x.replace('x', 'x_array')
    V_x = eval(V_x)

    # Calculate finite difference elements
    dt = t_array[1] - t_array[0]
    dx = x_array[1] - x_array[0]

    # Put V(x) array values into the diagonal elements of an empty matrix
    V_x_matrix = diags(V_x)

    # Calculate the Hamiltonian matrix
    H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + V_x_matrix

    # Apply boundary conditions to the Hamiltonian
    H[0, :] = H[-1, :] = 0
    H[0, 0] = H[-1, -1] = 1

    # Calculate U
    I_plus = eye(Nx) + 1j * dt / 2. * H
    I_minus = eye(Nx) - 1j * dt / 2. * H
    U = inv(I_minus).dot(I_plus)

    # Iterate over each time, appending each calculation of psi to a list
    psi_list = []
    for t in t_array:
        psi = U.dot(psi)
        psi[0] = psi[-1] = 0
        psi_list.append(np.abs(psi))

    return x_array, t_array, V_x, psi_list       

# Calls return arrays in my_func
x_array, t_array, V_x, psi_list = my_func()

# Saves key data into a pandas data frame 
df = pd.DataFrame({'x': x_array, 'time': t_array, 'V(x)': V_x, 'psi': psi_list})



###Plotting###

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(x_array, psi_list[0], lw=2)
ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color = "C10")
ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 2)
ax.grid()

# Creaes plot for V_x
ax_twin = ax.twinx()
line_2, = ax_twin.plot(x_array, V_x, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

# adjust the main plot to make room for the sliders and boxes
fig.subplots_adjust(left=0.25, bottom=0.25)



###Widgets for plot###

# Allows user to input a function for V_x on the plot
initial_text = 'x**2'
def submit(text):

    global V_x

    V_x = eval(text.replace('x', 'x_array'))
    line_2.set_ydata(V_x)
    plt.draw()

axbox = plt.axes([0.13, 0.9, 0.4, 0.075])
text_box = TextBox(axbox, 'Input V(x)', initial=initial_text)
text_box.on_submit(submit)


# Make a horizontal slider to control the Nx and Nt.
axNxNt = fig.add_axes([0.25, 0.07, 0.65, 0.03])
NxNt_slider = Slider(
    ax=axNxNt,
    label='Nx = Nt',
    valmin=0,
    valmax=len(x_array),
    valinit=50,)


# Make a horizontal slider to control the time evolution.
axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
time_slider = Slider(
    ax=axTime,
    label='Time',
    valmin=0,
    valmax=len(t_array) - 1,
    valinit=0,
    slidermax= NxNt_slider,)


# The function to be called anytime a slider's value changes
def update(val):

    global x_array, t_array, psi_list

    x_array, t_array, V_x, psi_list = my_func(Nx=int(NxNt_slider.val))
    
    line.set_xdata(x_array)
    line.set_ydata(psi_list[int(time_slider.val)])
    fig.canvas.draw_idle()

# Register the update function with each slider
time_slider.on_changed(update)
NxNt_slider.on_changed(update)


# Create a Button to allow user to download data in csv file.
dataax = fig.add_axes([0.8, 0.025, 0.18, 0.04])
button1 = Button(dataax, 'Download Data?', hovercolor='0.975')

def download_data(event):

    df = pd.DataFrame({'x': x_array, 'time': t_array, 'V(x)': V_x, 'psi': psi_list})
    df.to_csv('psi_data.csv')

button1.on_clicked(download_data)


# Create a Button to allow user to download an animated gif, then closes app or will freeze!
gifax = fig.add_axes([0.1, 0.025, 0.18, 0.04])
button2 = Button(gifax, 'Gif Download?', hovercolor='0.975')

def gif(event):

    # Creates a gif of the simulated data and saves it if button is clicked
    def run(psi):
        line.set_data(x_array, np.abs(psi)**2)
        return line,

    ani = animation.FuncAnimation(fig, run, psi_list, interval=10)
    ani.save("particle_in_a_well.gif", fps=120, dpi=300) 

    plt.close()

button2.on_clicked(gif)


plt.show()
`

**Comment by Zhap053** [comment]
bit buggy ...but could be really cool if this could work.

**Comment by Zhap053** [comment]
ill upload the code on the alternative code branch as ...'Slider_2'

**Comment by Zhap053** [comment]
I think it is something to do with the V(x) array I have created

**Comment by charlotteharrison1** [comment]
> bit buggy ...but could be really cool if this could work.

what are you trying to do with it?

**Comment by Zhap053** [comment]
> 

A user should be able to ...]

- input different potential inside that top box.
- change the time evolution with the slider (but not further than the Nx and Nt slider)
- change the Nx and Nt with the slider 
- Download gif of an animation of the time evolution with click of a button
- Download the data of x,t,V(x),psi(x,t) into a csv file.

... when using the application.

**Comment by charlotteharrison1** [comment]
> A user should be able to ...]
> 
> * input different potential inside that top box.
> * change the time evolution with the slider (but not further than the Nx and Nt slider)
> * change the Nx and Nt with the slider
> * Download gif of an animation of the time evolution with click of a button
> * Download the data of x,t,V(x),psi(x,t) into a csv file.
> 
> ... when using the application.

I see! with regards to inputting the potential, I could try applying the box thing to the original code, since the inputs work there

**Comment by charlotteharrison1** [comment]
> > A user should be able to ...]
> > 
> > * input different potential inside that top box.
> > * change the time evolution with the slider (but not further than the Nx and Nt slider)
> > * change the Nx and Nt with the slider
> > * Download gif of an animation of the time evolution with click of a button
> > * Download the data of x,t,V(x),psi(x,t) into a csv file.
> > 
> > ... when using the application.
> 
> This runs smoothly, but you need to manually input a V from the terminal first, then you can update it using the text box 

```
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
from matplotlib.widgets import TextBox
import pandas as pd


# Input parameters
Nx = 500

#defining space & time variables
xmin = -5
xmax = 5
Nt = 500
tmin = 0
tmax = 60


# Calculate grid, potential, and initial wave function
x_array = np.linspace(xmin, xmax, Nx)
t_array = np.linspace(tmin, tmax, Nt)


# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()

'''
READ BEFORE INPUTTING POTENTIALS
When inpuuting own potentials use the variable x_array
Numpy packages can be used to form a string as the potential
'''

#defining a default f(x), which will act as potential in case of no user input. replaced by user input in V()
def f(x_array):
    return x_array**2

             

#allowing user to define V via a widget on the plot 

###Widgets for plot###

# Allows user to input a function for V_x on the plot





VV = x_array**2
    

def V():
      String = str(input("Please input potential\n"))
      command = """def f(x):
          return """ + String
      
      exec(command, globals())
      
      return f(x_array)
  
VV = V()
    
axbox = plt.axes([0.13, 0.9, 0.4, 0.075])
text_box = TextBox(axbox, 'Input V(x)')
text_box.on_submit(VV)







'''
Converting V into a Daiognal matrix and calculating small psi
'''
Vmatrix = diags(VV)
psi = np.exp(-(x_array+2)**2)

dt = t_array[1] - t_array[0]
dx = x_array[1] - x_array[0]

H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + Vmatrix

'''
Apply boundary conditions to the Hamiltonian
'''

H[0, :] = H[-1, :] = 0
H[0, 0] = H[-1, -1] = 1

'''
Calculating U
'''

I_plus = eye(Nx) + 1j * dt / 2. * H
I_minus = eye(Nx) - 1j * dt / 2. * H
U = inv(I_minus).dot(I_plus)


# making a list of all the calculations
psi_list = []
for t in t_array:
    psi = U.dot(psi)
    psi[0] = psi[-1] = 0
    psi_list.append(np.abs(psi))


ax.set_xlabel("x [arb units]")
ax.set_ylabel("$|\Psi(x, t)|$", color="C0")

ax_twin = ax.twinx()
ax_twin.plot(x_array, VV, color="C1")
ax_twin.set_ylabel("V(x) [arb units]", color="C1")

line, = ax.plot([], [], color="C0", lw=2)
ax.grid()
xdata, ydata = [], []

def run(psi):
    line.set_data(x_array, np.abs(psi)**2)
    return line,

ax.set_xlim(x_array[0], x_array[-1])
ax.set_ylim(0, 1)

ani = animation.FuncAnimation(fig, run, psi_list, interval=10)

plt.show()

```

**Comment by charlotteharrison1** [comment]
> def V():
>       String = str(input("Please input potential\n"))
>       command = """def f(x):
>           return """ + String
>       
>       exec(command, globals())
>       
>       return f(x_array)
>   
> VV = V()
>     
> axbox = plt.axes([0.13, 0.9, 0.4, 0.075])
> text_box = TextBox(axbox, 'Input V(x)')
> text_box.on_submit(VV)

Ok, I actually don't think this is possible, at least not for me to do. If I'm right, the code itself it built upon V, so to replace it would require rerunning it anyway, defeating the point of the text box. Even when the text is being edited in your original code, I suspect you're just editing the contents of the text box, not the actual input

**Comment by Zhap053** [comment]
I've tried putting your code in mine but have had difficulty getting it to work. 

Plus, I can't seem to fix the bug in my code either.  Sorry. I have really tried.

**Comment by charlotteharrison1** [comment]
> I've tried putting your code in mine but have had difficulty getting it to work.
> 
> Plus, I can't seem to fix the bug in my code either. Sorry. I have really tried.

That's ok!! 

Since the project is due tomorrow however, if you're happy with the code in solving_TDSE could you possibly work on some of the other open issues?

**Comment by Zhap053** [comment]
I think actually this works quite well...

**Comment by Zhap053** [comment]
`from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.pyplot as plt
from findiff import FinDiff
from scipy.sparse.linalg import inv
from scipy.sparse import eye, diags
import matplotlib.animation as animation
from matplotlib.widgets import TextBox
import pandas as pd
plt.rcParams["axes.labelsize"] = 16


###Generating data###
def psi_plotter():

    try:
        print("Please input your V(x)")
        print("You may use numpy functions if you wish.")
        V_x = input("")
        
        def my_func(Nx=500, xmin=-5, xmax=5, tmin=0, tmax=20, V_x=V_x):

            # Calculate grid, and initial wave function
            Nt = Nx
            x = np.linspace(xmin, xmax, Nx)
            t_array = np.linspace(tmin, tmax, Nt)
            psi = np.exp(-(x+2)**2)
            # Create potential equation with user input
            V_x = eval(V_x)

            # Calculate finite difference elements
            dt = t_array[1] - t_array[0]
            dx = x[1] - x[0]

            # Put V(x) array values into the diagonal elements of an empty matrix
            V_x_matrix = diags(V_x)

            # Calculate the Hamiltonian matrix
            H = -0.5 * FinDiff(0, dx, 2).matrix(x.shape) + V_x_matrix

            # Apply boundary conditions to the Hamiltonian
            H[0, :] = H[-1, :] = 0
            H[0, 0] = H[-1, -1] = 1

            # Calculate U
            I_plus = eye(Nx) + 1j * dt / 2. * H
            I_minus = eye(Nx) - 1j * dt / 2. * H
            U = inv(I_minus).dot(I_plus)

            # Iterate over each time, appending each calculation of psi to a list
            psi_list = []
            for t in t_array:
                psi = U.dot(psi)
                psi[0] = psi[-1] = 0
                psi_list.append(np.abs(psi))

            return x, t_array, V_x, psi_list


        # Calls return arrays in my_func
        x, t_array, V_x, psi_list = my_func()

        # Saves key data into a pandas data frame
        df = pd.DataFrame({'x': x, 'time': t_array,
                        'V(x)': V_x, 'psi': psi_list})


        ###Plotting###

        # Create the figure and the line that we will manipulate
        fig, ax = plt.subplots()
        line, = ax.plot(x, psi_list[0], lw=2)
        ax.set_xlabel("x [arb units]")
        ax.set_ylabel("$|\Psi(x, t)|$", color="C10")
        ax.set_xlim(x[0], x[-1])
        ax.set_ylim(0, 2)
        ax.grid()

        # Creaes plot for V_x
        ax_twin = ax.twinx()
        line_2, = ax_twin.plot(x, V_x, color="C1")
        ax_twin.set_ylabel("V(x) [arb units]", color="C1")

        # adjust the main plot to make room for the sliders and boxes
        fig.subplots_adjust(left=0.25, bottom=0.25)


        ###Widgets for plot###


        # Make a horizontal slider to control the Nx and Nt.
        axNxNt = fig.add_axes([0.25, 0.07, 0.65, 0.03])
        NxNt_slider = Slider(
            ax=axNxNt,
            label='Nx = Nt',
            valmin=0,
            valmax=len(x),
            valinit=50,)


        # Make a horizontal slider to control the time evolution.
        axTime = fig.add_axes([0.25, 0.1, 0.65, 0.03])
        time_slider = Slider(
            ax=axTime,
            label='Time',
            valmin=0,
            valmax=len(t_array) - 1,
            valinit=0,
            slidermax=NxNt_slider,)


        # The function to be called anytime a slider's value changes
        def update(val):

            x, t_array, V_x, psi_list = my_func(Nx=int(NxNt_slider.val))

            line.set_xdata(x)
            line.set_ydata(psi_list[int(time_slider.val)])
            fig.canvas.draw_idle()


        # Register the update function with each slider
        time_slider.on_changed(update)
        NxNt_slider.on_changed(update)


        # Create a Button to allow user to download data in csv file.
        dataax = fig.add_axes([0.8, 0.025, 0.18, 0.04])
        button1 = Button(dataax, 'Download Data?', hovercolor='0.975')


        def download_data(event):

            df = pd.DataFrame({'x': x, 'time': t_array,
                            'V(x)': V_x, 'psi': psi_list})
            df.to_csv('psi_data.csv')


        button1.on_clicked(download_data)


        # Create a Button to allow user to download an animated gif, then closes app or will freeze!
        gifax = fig.add_axes([0.1, 0.025, 0.18, 0.04])
        button2 = Button(gifax, 'Gif Download?', hovercolor='0.975')


        def gif(event):

            # Creates a gif of the simulated data and saves it if button is clicked
            def run(psi):
                line.set_data(x, np.abs(psi)**2)
                return line,

            ani = animation.FuncAnimation(fig, run, psi_list, interval=10)
            ani.save("particle_in_a_well.gif", fps=120, dpi=300)

            plt.close()


        button2.on_clicked(gif)


        plt.show()
    
    except:
        print("\nV(x) input does not compute.")
        print("Please input a valid mathematical equation in terms of x.")
        print("\nSome examples:")
        print("... x**2")
        print("np.sin(x)")
        print("\nClosing programme.")
        exit()

psi_plotter()`

**Comment by Zhap053** [comment]
charlotteharrison1 ... you may want to give your input equation ago in this code. I think it should work... if you fancy it.

**Comment by Zhap053** [comment]
It also has an input error catch. Nothing to fancy but something to alert the user they have done something wrong

**Comment by Zhap053** [comment]
would be cool if some people could give it a try and see if they like the code. It could be a candidate for the main branch.

**Comment by Zhap053** [comment]
it's called slider_3 in alternative code branch

**Comment by charlotteharrison1** [comment]
this seems good but I'm afraid I don't have time to do the tests myself and do the remaining packaging on my own. If you can improve what we have already and also help with that remaining work then please go ahead, but I'm going to focus on the existing issues given that we have less than 24 hours.

> charlotteharrison1 ... you may want to give your input equation ago in this code. I think it should work... if you fancy it.

**Comment by Zhap053** [comment]
No worries. I've made a few improvements on the main code.

**Comment by charlotteharrison1** [comment]
> No worries. I've made a few improvements on the main code.

thanks for that. I hope it's ok that I'm going to close this issue now
