### ISSUE TITLE
Frequency of the psi wave 

### ISSUE THREAD

**Issue by Zhap053** [CharlieRoss2506/actualgroupproject#36]
I believe we need to estimate the frequency of the un periodic wave generated by our data for psi. I think this can be done with Fourier transforms. 

I have found this book which may help us do this in python 

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter24.02-Discrete-Fourier-Transform.html

**Comment by charlotteharrison1** [comment]
I think I recall doing something like this in the notebooks before, but I don't know that it's necessary for this project, although I'm sure it can't hurt
