### ISSUE TITLE
decide on best visualisation of psi

### ISSUE THREAD

**Issue by charlotteharrison1** [CharlieRoss2506/actualgroupproject#9]

**Comment by charlotteharrison1** [comment]
- [x] animation
- [x] image
- [x] plot

**Comment by charlotteharrison1** [comment]
visualisation using an image looks like this:

![image](https://user-images.githubusercontent.com/116881713/201338437-35f7e8c4-6774-4f9a-8ada-2dc0f8ac951c.png)

**Comment by charlotteharrison1** [comment]
plotting returns:

for t-axis:
![image](https://user-images.githubusercontent.com/116881713/201338801-22ad9752-7599-4b79-b2b2-6d358bd37636.png)


for x-axis:
![image](https://user-images.githubusercontent.com/116881713/201338835-fb2c02df-dcce-413c-a7b1-136a0ba33d4e.png)




these look pretty much the same; the best visualisation will incorporate all of the x, t, and V dependence

**Comment by charlotteharrison1** [comment]
plotting V-dependence

![image](https://user-images.githubusercontent.com/116881713/201339289-dd4fbbbb-0cf9-4ed5-a4d3-732f89540ac6.png)

**Comment by CharlieRoss2506** [comment]
The graphs works best with the animation but we could have an option for sliders on a still image, like Luca sent over

**Comment by CharlieRoss2506** [comment]
Did the animation side of the code work??
